### ISSUE TITLE
auto_complete false breaks completion

### ISSUE THREAD

**Issue by tex** [Shougo/deoplete.nvim#1006]
When auto_complete is false then first time completion is triggered with <TAB> only A and B sources are shown, no candidates from LSP. Second time completion is triggered with <TAB> all sources' candidates are shown. When auto_complete is true it works as expected, all sources' candidates are shown. But I do not want auto complete turn on, I want to trigger completion when I want. It used to work correctly week ago.

```
call deoplete#custom#option({
    \ 'auto_complete': v:false,
    \ })
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ deoplete#manual_complete()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

if executable('ccls')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'ccls',
      \ 'cmd': {server_info->['ccls']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
      \ 'initialization_options': {},
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
      \ })
endif
```

**Comment by Shougo** [comment]
Why don't upload the minimal vimrc?
I cannot reproduce the problem.

I can close the issue later if you don't upload it.

**Comment by tex** [comment]
Sorry, you are rigth. Minimal configuration works so it has to be some other plugin that breaks it.

**Comment by Shougo** [comment]
OK.

**Comment by tex** [comment]
It is yours neoinclude plugin that does that. When I disabled it it works, when I enabled it it does what I described in this issue.

**Comment by tex** [comment]
Well, it happens even with minimal config, but just occasionaly. Looks like some timing issue... Like once every 3-5 attempts.

```
if has('nvim')
    if empty(glob('~/.config/nvim/autoload/plug.vim'))
        silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
                    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        autocmd VimEnter * PlugInstall | source ~/.config/nvim/init.vim
    endif
else
    if empty(glob('~/.vim/autoload/plug.vim'))
        silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        autocmd VimEnter * PlugInstall | source ~/.vimrc
    endif
endif

call plug#begin('~/.vim/plugged')

Plug 'prabirshrestha/async.vim'
Plug 'https://github.com/Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'https://github.com/prabirshrestha/vim-lsp.git'
Plug 'https://github.com/lighttiger2505/deoplete-vim-lsp.git'
call plug#end()

call deoplete#custom#option({
    \ 'auto_complete': v:false,
    \ 'auto_complete_delay': 800,
    \ 'smart_case': v:true,
    \ })

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ deoplete#manual_complete()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

if executable('ccls')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'ccls',
      \ 'cmd': {server_info->['ccls']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
      \ 'initialization_options': {},
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
      \ })
endif

set completeopt-=preview
set shortmess+=c

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
```

**Comment by tex** [comment]
It looks like once pum is visible it does not get updated with candidates from the LSP source.

**Comment by Shougo** [comment]
Please use the latest version of deoplete.

**Comment by Shougo** [comment]
I don't want to test LSP source.

LSP source is really needed?

You can add the delay in around source like this.

```diff
diff --git a/rplugin/python3/deoplete/source/around.py b/rplugin/python3/deoplete/source/around.py
index 3a7a230..6f9ba38 100644
--- a/rplugin/python3/deoplete/source/around.py
+++ b/rplugin/python3/deoplete/source/around.py
@@ -5,6 +5,7 @@
 # ============================================================================

 import re
+import time

 from deoplete.base.source import Base
 from deoplete.util import parse_buffer_pattern, getlines
@@ -70,5 +71,6 @@ class Source(Base):
         candidates += [
             {'word': x, 'menu': self.vars['mark_below']} for x in words
         ]
+        time.sleep(2.0)

         return candidates
```

I have added the delay, but I don't reproduce the problem.

**Comment by Shougo** [comment]
Warning:

You have not upload the reproduce instructions.
I can ignore your issue.

**Comment by Shougo** [comment]
> It looks like once pum is visible it does not get updated with candidates from the LSP source.

No.  It is updated for me.  I have tested.

> Well, it happens even with minimal config, but just occasionaly. Looks like some timing issue... Like once every 3-5 attempts.

I have tested many times.  Not reproduced.

**Comment by Shougo** [comment]
I don't work for non reproduce-able problems.
It is my policy.

**Comment by Shougo** [comment]
> It used to work correctly week ago.

Hm.  It seems same problem with this.

https://github.com/Shougo/deoplete.nvim/issues/1007

OK.  I can close it.
Please use the latest version.

**Comment by tex** [comment]
Unfortunately even with latest version the problem is here. You are right that adding sleep to the A source works as expected, ie. candidates are shown a bit later. The problem with LSP is still here though, so I am going to look at the LSP source. Perhaps problem is there. Thanks for your help.

**Comment by tex** [comment]
Hi Shougo,

Commit 7556628fe4a7c57968b17580d038586b004526e3 causes that problem.

**Comment by Shougo** [comment]
So.

> It used to work correctly week ago.

This is your mistake?

That commit exists week ago.

**Comment by tex** [comment]
Yep. It was my mistake :) Time flows so fast!

**Comment by Shougo** [comment]
I need the reason.

Please check why the code causes the problem.

The commit is needed for https://github.com/Shougo/deoplete.nvim/issues/976

It may be deoplete-vim-lsp problem.

**Comment by Shougo** [comment]
The revert is not the real fix.

**Comment by tex** [comment]
Changing a bit the deoplete-vim-lsp provides acceptable results. I consider this an "API" change so the deoplete-vim-lsp change is needed and it is not per se deoplete issue.

**Comment by lighttiger2505** [comment]
@tex 

> Changing a bit the deoplete-vim-lsp provides acceptable results.

Please tell me the change.

Adding sleep to gather_candidates in deoplete-vim-lsp solves the problem, but it is not the best solution.
I am interested in your solution.

If you can create an MR, it is best.

**Comment by tex** [comment]
@shougo So I think it is deoplete issue afterall. Or example of async plugin in deoplete.txt is wrong and needs to be fixed. I tried it and I see that it counts up to 2 first time, second time it shows 10 candidates as it should.

**Comment by tex** [comment]
@lighttiger2505 My fix is essentially a sleep :) wait until `deoplete#source#vim_lsp#_requested` is set.

**Comment by tex** [comment]
@Shougo  I tried example async source as it is in deoplete.txt and it behaves unpredictable: sometime it shows just 2 candidates for first time, sometimes it shows all candidates as it should. Second time it shows proper number of candidates. I think that async sources are broken and problem is in deoplete itself.

**Comment by Shougo** [comment]
@tex Please upload the reproduce instructions with the minimal vimrc instead of description.
I need to reproduce.  If not, I can ignore your issue.

**Comment by Shougo** [comment]
@tex Please read other issues and issue template.
We have no ESP skills.

**Comment by Shougo** [comment]
For example, this is reproduce-able with minimal vimrc.
Please compare with your report.

https://github.com/Shougo/deoplete.nvim/issues/975

**Comment by Shougo** [comment]
I have tested and it works expected.
Please describe the problem more clearly.

**Comment by tex** [comment]
Hi @Shougo, I am trying to understang how it works, please look at this recording: https://asciinema.org/a/bYoFZgL1MuFLtIAzriHt3ZuHY
How to make it work even when I want completion after '.' character?

**Comment by lighttiger2505** [comment]
@tex I have fixed.
This change is patchwork but should work almost as you wish.

https://github.com/lighttiger2505/deoplete-vim-lsp/pull/12

**Comment by tex** [comment]
@lighttiger2505 thanks, will try it
@Shougo I'd like to know why https://asciinema.org/a/bYoFZgL1MuFLtIAzriHt3ZuHY behaves as recorded. I would expect that with '.' it should works same as for other cases.

**Comment by Shougo** [comment]
@tex It is bug.  Reproduced for me.  But it is hard to fix.
I have added workaround.  It is not perfect fix.

I think `is_async` is not recommended.
It is not so useful and broken.  You should use callback system instead.

**Comment by tex** [comment]
Thanks!
Still does not work - after '.' it shows now only '.9', '.10'. or '.8','.9','.10'.
But I understand that `is_async` is depreceated and not to be used by sources which is fine and it is good you added that information to documentation.

**Comment by Shougo** [comment]
I have reverted the workaround.
Please see #1013.
