### ISSUE TITLE
deoplete error when using fern.vim on Windows

### ISSUE THREAD

**Issue by jdhao** [Shougo/deoplete.nvim#1165]
# Problems summary

When using deoplete, together with [deoplete-vim-lsp](https://github.com/lighttiger2505/deoplete-vim-lsp) and [fern.vim](https://github.com/lambdalisue/fern.vim), when I open the fern.vim file browser, I see errors related to paths.

## Expected

No errors.

## Environment Information

 * deoplete version (SHA1): 27af4ab2de157f80c8a8391aebb60061318814ea

 * OS: Windows 10

 * neovim/Vim `:version` output: NVIM v0.5.0-dev+1007-g9223d1450

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 <details>
 <summary><font size="2" color="red">checkhealth output</font></summary>
 
 ```
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github
 
 ```
 </details>

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=C:\Users\Administrator\AppData\Local\nvim-data\plugged\deoplete.nvim
set runtimepath+=C:\Users\Administrator\AppData\Local\nvim-data\plugged\deoplete-vim-lsp
set runtimepath+=C:\Users\Administrator\AppData\Local\nvim-data\plugged\fern.vim

let g:loaded_python_provider=0
let g:python3_host_prog=exepath('python')

" Wheter to enable deoplete automatically after start nvim
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Use the above minimal config to start nvim: `nvim -u init.vim`
 2. Open fern.vim using `Fern .`

The error tracestack is:

```
error caught in async handler 'deoplete_on_event [{'rpc': 'deoplete_on_event', 'event': 'BufEnter', 'sources': ['lsp']}]'
Traceback (most recent call last):
  File "C:/Users/Administrator/AppData/Local/nvim-data/plugged/deoplete.nvim/rplugin/python3\deoplete\__init__.py", line 50, in on_event
    self._deoplete.on_event(context)
  File "C:/Users/Administrator/AppData/Local/nvim-data/plugged/deoplete.nvim/rplugin/python3\deoplete\deoplete.py", line 143, in on_event
    self._context._init_cached()
  File "C:/Users/Administrator/AppData/Local/nvim-data/plugged/deoplete.nvim/rplugin/python3\deoplete\context.py", line 84, in _init_cached
    if not Path(bufpath).exists() or 'nofile' in buftype:
  File "D:\Anaconda\lib\pathlib.py", line 1334, in exists
    self.stat()
  File "D:\Anaconda\lib\pathlib.py", line 1156, in stat
    return self._accessor.stat(self)
  File "D:\Anaconda\lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'd:\\code_exprt\\fern:\\dbe76268\\file:\\d:\\code_exprt$'

```

**Comment by Shougo** [comment]
Fixed.

**Comment by jdhao** [comment]
@Shougo  The exception catching [here](https://github.com/Shougo/deoplete.nvim/commit/17772ff46ab625901697e23635dd72cfad7e393c#diff-6020d9ce37b89d6b5606e697de44a3a37bcf1cffe52ec317e3bbcc5722bfb7a7R229) is incorrect. It should be `OSError` instead of `RuntimeError`. The above error still persists.

**Comment by Shougo** [comment]
Oh, no.

Fixed again.  Please use the latest version.
