### ISSUE TITLE
After Update Via VIM Plug, Errors Staring NeoVIM

### ISSUE THREAD

**Issue by PorcelainMouse** [Shougo/deoplete.nvim#513]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
All I did was :PlugUpdate and now nvim gives many errors start.

## Expected
no errors, was working immediately before update of deoplete.

## Environment Information

 * deoplete version(SHA1):
4ea277c8eaa2525f9f1d0d19340c6c55e23f467e
 * OS:
Linux 4.11.8-200.fc25.x86_64
 * neovim version:
NVIM v0.2.0
 * `:CheckHealth` result(neovim ver.0.1.5-452+):

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 10ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python3 version: 3.5.3
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Provide a minimal init.vim with less than 50 lines (Required!)

" NeoVim Config file
"" Completion Configuration
" Use deoplete.
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim/
call deoplete#enable()
"let g:deoplete#enable_at_startup = 1

## The reproduce ways from neovim starting (Required!)

 1. nvim

## Generate a logfile if appropriate

Happens on start up.  Do you need log file?

**Comment by Shougo** [comment]
Please execute `:UpdateRemotePlugins` command.

**Comment by PorcelainMouse** [comment]
I get this
:UpdateRemotePlugins
remote/host: python3 host registered plugins ['deoplete'] 
remote/host: generated rplugin manifest: /home/<username>/.local/share/nvim/rplugin.vim

but, quitting and restarting nvim gives I think the same results
Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[9]..deoplete#init#_channel:
line   31:
E121: Undefined variable: g:deoplete#_channel_id
E116: Invalid arguments for function rpcnotify
Press ENTER or type command to continue

I did have VIM Plug configured as 
Plug 'shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' } 
previously.

Thanks for helping so quick!  Please forgive me if I've missed something obvious.

**Comment by Shougo** [comment]
Your deoplete is broken.
I cannot reproduce the problem and `deoplete#init#_channel()` Line 31 does not have `g:deoplete#_channel_id`.
You can check the source code in github.
You should reinstall deoplete.nvim.

**Comment by PorcelainMouse** [comment]
Hmm.  I removed deoplete.vim from Plug list, ran PlugClean, 'Y' for yes delete whole directory, restored Plug line for deoplete.vim, and reinstalled with PlugInstall and got exactly the same results.

Now I'm at 45f7d8e47fadb1be762b49a17704069c11b8a8bd , though.  On line 32 I see this:

call rpcnotify(g:deoplete#_channel_id, 
\ 'deoplete_enable_logging', a:level, a:logfile) 

Isn't that consistent with this error states?

**Comment by Shougo** [comment]
Logging...  OK.  Your minimal vimrc is wrong.

**Comment by PorcelainMouse** [comment]
I'm double checking it, now....

**Comment by Shougo** [comment]
Fixed.

**Comment by PorcelainMouse** [comment]
Okay, I think I found the error.  But, still no joy.

$ cat minimal.vim 
" Your minimal init.vim
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
pdestefa@wrangler ~/.../nvim 15T20:27$ nvim -u ./minimal.vim
Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[9]..deoplete#init#_channel:
line   31:
E121: Undefined variable: g:deoplete#_channel_id
E116: Invalid arguments for function rpcnotify
Press ENTER or type command to continue
...
$ ls  ~/.local/share/nvim/plugged/deoplete.nvim/
autoload/  doc/  LICENSE  Makefile  plugin/  README.md  rplugin/  test/

Sorry about this and thanks for helping me!  But, I still don't understand what I'm doing wrong.

**Comment by PorcelainMouse** [comment]
oh, cool!  Sorry.  just clicked as you posted!

**Comment by PorcelainMouse** [comment]
I'll update.

**Comment by PorcelainMouse** [comment]
I'm so so sorry.  I'm really confused and still stuck.

I deleted everything again and reinstalled it, but still get exactly same result.  

I have the commit you just pushed.
$ git rev-parse HEAD
2740a789939e8f13731e8cb34a06b602eef2a744

But...

$ cat minimal.vim 
" Your minimal init.vim
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim/
"let g:deoplete#enable_at_startup = 1
$ ls ~/.local/share/nvim/plugged/deoplete.nvim/
autoload/  doc/  LICENSE  Makefile  plugin/  README.md  rplugin/  test/
$ nvim -u ./minimal.vim 

(In NeoVIM, I ran :call deoplete#enable() )

Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[9]..deoplete#init#_channel:
line   31:
E121: Undefined variable: g:deoplete#_channel_id
E116: Invalid arguments for function rpcnotify
Press ENTER or type command to continue

I used logging to make you this log.  Notice, there isn't any reference to line 31 in the log.

[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/1150828/log_py3_rplugin.txt)

**Comment by Shougo** [comment]
Really?
I'm very doubtful for your report.  I don't get the same error report yet.  Why?
Because, the error line number is wrong.

Please upload the screenshot.

Note: You can check the line number.  It is the open source.

**Comment by Shougo** [comment]
If other people said about the same error, I will check it.
But it is only you now.

**Comment by Shougo** [comment]
And `deoplete#init#_check_channel()` checks `g:deoplete#_channel_id` existence.
So the error should not be occurred.
You should check the source code in your repository.

**Comment by Shougo** [comment]
Please install deoplete.nvim without Vim-plug.
It should be by your hand.
And add the runtimepath manually.

**Comment by PorcelainMouse** [comment]
Ah!  I had some old deoplete files in autoload/ not managed by vim-plug. It is interesting that these files did *not* show up in any of the error logs.  Error logs referred to the new, updated, vim-plug managed files.  That was a very tricky edge case.

Thanks for your help!!

**Comment by Shougo** [comment]
Ah, OK...
I have though it.
